import type { FlowStage } from './types';

// Etapas da Timeline (visão operacional por atividade).
export const FLOW_STAGES: FlowStage[] = [
  {
    id: 'semPrevEmbarque',
    idx: '01',
    name: 'Sem previsão de embarque',
    short: 'Sem prev. embarque',
    source: 'Ag. Envio Digitação',
    desc: 'Processos sem Previsão Embarque e sem Embarque informado.',
    criteria: 'Previsão Embarque vazia E Embarque vazio.',
    priority: '1º TA: NÃO ENVIADO → AGUARDANDO NCM → INEXISTENTE. 2º maior Qtd Dias Abertura.',
  },
  {
    id: 'semPrevChegada',
    idx: '02',
    name: 'Sem previsão de chegada',
    short: 'Sem prev. chegada',
    source: 'Ag. Envio Digitação',
    desc: 'Processos que já têm sinal de embarque, mas ainda não possuem Previsão Chegada.',
    criteria: 'Não entra em Sem previsão de embarque e Previsão Chegada está vazia.',
    priority: '1º TA: NÃO ENVIADO → AGUARDANDO NCM → INEXISTENTE. 2º maior Qtd Dias Abertura.',
  },
  {
    id: 'comPrevChegada',
    idx: '03',
    name: 'Com previsão de chegada',
    short: 'Com prev. chegada',
    source: 'Ag. Envio Digitação',
    desc: 'Processos com Previsão Chegada informada e sem sinal atual de espera documental do cliente.',
    criteria: 'Previsão Chegada válida. Sinais de espera documental do cliente vão para a etapa seguinte.',
    priority: '1º Previsão Chegada crescente. 2º TA. 3º maior Qtd Dias Abertura.',
  },
  {
    id: 'aguardandoCliente',
    idx: '04',
    name: 'Aguardando documentos do cliente',
    short: 'Ag. docs cliente',
    source: 'Ag. Envio Digitação',
    desc: 'Processos com previsão de chegada e sinal de dependência documental do cliente.',
    criteria:
      'Previsão Chegada válida E ANUENTE = AGUARDANDO NCM ou follow/observação indicando espera por cliente, documentos, cópia, HBL/BL, invoice, packing ou correção.',
    priority: '1º Previsão Chegada crescente. 2º Previsão Embarque. 3º follow mais antigo. 4º dias de abertura.',
  },
  {
    id: 'digitacao',
    idx: '05',
    name: 'Em digitação',
    short: 'Em digitação',
    source: 'Ag. Chegada / Chegada Confirmada',
    desc: 'Processos cuja digitação ainda está efetivamente pendente ou em envio para digitação.',
    criteria:
      'Digitação pendente e sem chegada crítica iminente. Processos com previsão de chegada válida e prontidão incompleta migram para a etapa crítica de chegada.',
    priority: 'Prazo de digitação vencido, hoje e próximos 3 dias.',
  },
  {
    id: 'numerario',
    idx: '06',
    name: 'Aguardando digitação e numerário',
    short: 'Ag. Digit+Num',
    source: 'Ag. Chegada / Chegada Confirmada',
    desc: 'Processos com pendência ativa de numerário (ou digitação+numerário) antes do marco crítico de chegada.',
    criteria:
      'Sinais de NÃO ENVIADO, AG. DEPÓSITO, DÉBITO CLIENTE ou autorização pendente. Com previsão de chegada válida e prontidão incompleta, migra para a etapa crítica seguinte. Pago/inexistente não permanece.',
    priority: 'Numerário vencido, chegada próxima/confirmada e bloqueios.',
  },
  {
    id: 'agChegadaPendente',
    idx: '07',
    name: 'Ag. chegada e com pendência',
    short: 'Ag. chegada c/ pend.',
    source: 'Ag. Chegada',
    desc: 'Chegada crítica: previsão de chegada válida, sem chegada confirmada e ainda sem prontidão operacional (digitação/numerário pendente).',
    criteria:
      'Presente em Ag. Chegada, com Previsão Chegada válida, sem chegada real e Digitação fora de CONFERIDO AG. CHEGADA / Conferência DI / Registro. Absorve os processos de Digitação/Numerário para evitar duplicação.',
    priority: 'Chegada mais próxima ou vencida primeiro; depois pendências de digitação/numerário e demais sinais.',
  },
  {
    id: 'conferencia',
    idx: '08',
    name: 'Conferência de DI',
    short: 'Conferência DI',
    source: 'Ag. Chegada / Chegada Confirmada',
    desc: 'Processos efetivamente em Conferência de DI.',
    criteria: 'Status/etapa com CONFERÊNCIA DI. Posicionada antes de Conferido aguardando chegada.',
    priority: 'Chegada confirmada, maior atraso operacional, hoje e próximos 3 dias.',
  },
  {
    id: 'conferidoAgChegada',
    idx: '09',
    name: 'Conferido aguardando chegada',
    short: 'Conferido ag. chegada',
    source: 'Ag. Chegada',
    desc: 'Digitação concluída e processo conferido, aguardando a chegada da carga.',
    criteria: 'Digitação = CONFERIDO AG. CHEGADA e ainda sem chegada confirmada.',
    priority: '1º previsão de chegada mais próxima. 2º sem previsão. 3º maior tempo de abertura.',
  },
  {
    id: 'chegadaPendente',
    idx: '10',
    name: 'Chegada confirmada com pendência',
    short: 'Chegada c/ pendência',
    source: 'Chegada Confirmada',
    desc: 'Processos com chegada já confirmada e mantidos no backlog por pendência posterior.',
    criteria: 'Presente na aba Chegada Confirmada com chegada real válida. A previsão de chegada deixa de ser pendência.',
    priority: 'Chegada mais antiga, digitação/numerário pendentes, sem presença, anuente ou mapa.',
  },
  {
    id: 'registro',
    idx: '11',
    name: 'Registro de DI',
    short: 'Registro DI',
    source: 'Chegada Confirmada / Registro com Pendência',
    desc: 'Processos aguardando registro ou com pendência de registro.',
    criteria: 'Aba Registro com Pendência, etapa Ag. registro ou Registro com Pendência.',
    priority: 'Pendência vencida, bloqueio, débito/depósito e chegada confirmada.',
  },
];

export const DASHBOARD_UNMAPPED_STAGE: FlowStage = {
  id: 'naoMapeado',
  idx: '—',
  name: 'Sem etapa mapeada',
  short: 'Sem etapa',
  source: '',
  desc: 'Processo ainda sem etapa da Timeline detectada.',
  criteria: '',
  priority: '',
};

export const DASHBOARD_STAGE_COLORS = [
  '#2C2D65', '#4B4C85', '#6B6DA4', '#8A6D9F', '#CE0F69',
  '#E35393', '#FF9E1B', '#D27D18', '#5B7F72', '#7B8794', '#AEB6C2',
];
